// <auto-generated />
namespace BoardGameInventory.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _40KStuffAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_40KStuffAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202201250008161_40KStuffAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
